version: '3.8'
name: ambulance-tracker

services:
  mysql:
    image: mysql:8.0
    container_name: ambulance-tracker-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ambulance_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eureka-server:
    container_name: ambulance-tracker-eureka
    build:
      context: .
      dockerfile: Dockerfile
      target: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  api-gateway:
    container_name: ambulance-tracker-gateway
    build:
      context: .
      dockerfile: Dockerfile
      target: api-gateway
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  ambulance-service:
    container_name: ambulance-tracker-ambulance
    build:
      context: .
      dockerfile: Dockerfile
      target: ambulance-service
    ports:
      - "8095:8095"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  dispatch-coordination-service:
    container_name: ambulance-tracker-dispatch
    build:
      context: .
      dockerfile: Dockerfile
      target: dispatch-service
    ports:
      - "8096:8096"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  hospital-management-service:
    container_name: ambulance-tracker-hospital
    build:
      context: .
      dockerfile: Dockerfile
      target: hospital-service
    ports:
      - "8093:8093"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  route-optimization-service:
    container_name: ambulance-tracker-route
    build:
      context: .
      dockerfile: Dockerfile
      target: route-service
    ports:
      - "8084:8084"
    depends_on:
      eureka-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ambulance_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  default:
    name: ambulance-tracker-network
    driver: bridge

volumes:
  mysql_data:
